# Generated by Django 4.2.2 on 2023-07-07 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvd_service', '0002_remove_cvdreport_officer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvdreport',
            name='email',
            field=models.EmailField(default=3, max_length=254),
            preserve_default=False,
        ),
    ]
