# Generated by Django 4.2.2 on 2023-07-05 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
